/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NFS_H_RPCGEN
#define _NFS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct bufwrap {
	char buffer[1024];
	u_int size;
};
typedef struct bufwrap bufwrap;

struct file_args_r {
	char filename[128];
	u_int offset;
	u_int size;
};
typedef struct file_args_r file_args_r;

struct file_args_w {
	char filename[128];
	u_int offset;
	char buffer[1024];
	u_int size;
};
typedef struct file_args_w file_args_w;

#define nfs_rpc 0x2fffffff
#define nfs 1

#if defined(__STDC__) || defined(__cplusplus)
#define nfs_write 1
extern  int * nfs_write_1(file_args_w *, CLIENT *);
extern  int * nfs_write_1_svc(file_args_w *, struct svc_req *);
#define nfs_read 2
extern  bufwrap * nfs_read_1(file_args_r *, CLIENT *);
extern  bufwrap * nfs_read_1_svc(file_args_r *, struct svc_req *);
extern int nfs_rpc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define nfs_write 1
extern  int * nfs_write_1();
extern  int * nfs_write_1_svc();
#define nfs_read 2
extern  bufwrap * nfs_read_1();
extern  bufwrap * nfs_read_1_svc();
extern int nfs_rpc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_bufwrap (XDR *, bufwrap*);
extern  bool_t xdr_file_args_r (XDR *, file_args_r*);
extern  bool_t xdr_file_args_w (XDR *, file_args_w*);

#else /* K&R C */
extern bool_t xdr_bufwrap ();
extern bool_t xdr_file_args_r ();
extern bool_t xdr_file_args_w ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NFS_H_RPCGEN */
