/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"


void
nfs_rpc_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	file_args_w  nfs_write_1_arg;
	bufwrap  *result_2;
	file_args_r  nfs_read_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, nfs_rpc, nfs, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	/*result_1 = nfs_write_1(&nfs_write_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = nfs_read_1(&nfs_read_1_arg, clnt);
	if (result_2 == (bufwrap *) NULL) {
		clnt_perror (clnt, "call failed");
	}*/
	while(1)
	{
		int k;
		printf("Press 1 to read and 2 to write\n");
		scanf("%d",&k);
		if(k==1)
		{
			printf("Enter filename: ");
			scanf("%s",nfs_read_1_arg.filename);
			scanf("%d",&nfs_read_1_arg.offset);
			scanf("%d",&nfs_read_1_arg.size);
			result_2 = nfs_read_1(&nfs_read_1_arg, clnt);
			if (result_2 == (bufwrap *) NULL) {
			clnt_perror (clnt, "call failed");
			}
			printf("Read %d bytes\n", result_2->size);
			printf("%s\n", result_2->buffer);
		}
		else if(k==2)
		{
			printf("Enter filename: ");
			scanf("%s",nfs_write_1_arg.filename);
			scanf("%d",&nfs_write_1_arg.offset);
			scanf("%d",&nfs_write_1_arg.size);
			printf("Enter Message to be written : ");
			scanf("%s",nfs_write_1_arg.buffer);
			result_1 = nfs_write_1(&nfs_write_1_arg, clnt);
			if (result_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
			printf("%d bytes written to %s\n",*result_1,nfs_write_1_arg.buffer);
	}

		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	nfs_rpc_1 (host);
exit (0);
}
