/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "fact.h"

bool_t
xdr_for_factorial (XDR *xdrs, for_factorial *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->num))
		 return FALSE;
	return TRUE;
}
