/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fact.h"


void
fact_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	for_factorial  fact_calc_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, FACT, FACT_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	printf("enter the number for factorial\n");
	scanf("%d",&fact_calc_1_arg.num);

	result_1 = fact_calc_1(&fact_calc_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("factorial is :%d\n",*result_1 );
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	fact_1 (host);
exit (0);
}
