/********************************************************
* Author 	: Sachin Govind
* Date   	: 20 February 2016 (Saturday)
* Title		: TCP client
********************************************************/
// Info : Implements an echo client what is written in server is displayed in client
// and what is written in client is displayed in server connects to Echo_Server.c
//Basic structures :
/*
#include <netinet/in.h>

struct sockaddr_in {
    short            sin_family;   // e.g. AF_INET
    unsigned short   sin_port;     // e.g. htons(3490)
    struct in_addr   sin_addr;     // see struct in_addr, below
    char             sin_zero[8];  // zero this if you want to
};

struct in_addr {
    unsigned long s_addr;  // load with inet_aton()
    inet_aton() returns non-zero if the address is a valid one, and it returns zero if the address is invalid.
};

The hostent structure is defined in <netdb.h> as follows:

           struct hostent {
               char  *h_name;            /* official name of host 
               char **h_aliases;         /* alias list 
               int    h_addrtype;        /* host address type 
               int    h_length;          /* length of address 
               char **h_addr_list;       /* list of addresses 
           }
           #define h_addr h_addr_list[0] /* for backward compatibility 

       The members of the hostent structure are:

       h_name The official name of the host.

       h_aliases
              An array of alternative names for the host, terminated by a
              null pointer.

       h_addrtype
              The type of address; always AF_INET or AF_INET6 at present.

       h_length
              The length of the address in bytes.

       h_addr_list
              An array of pointers to network addresses for the host (in
              network byte order), terminated by a null pointer.

       h_addr The first address in h_addr_list for backward compatibility.

*/

#include <sys/types.h>
#include <netinet/in.h>
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <arpa/inet.h> //for big-endian ordering of number htonl number
#include <string.h>
#include <errno.h>
#include <netdb.h>
#include <sys/socket.h>

#define maxd 100 //max data length
int main()
{
	//sfd and bytes recieved
	int sfd,bytes_recv;
	//to send data to server
	char send_data[maxd],recv_data[maxd];
	struct sockaddr_in server_addr,client_addr;
	struct hostent * host; //see above
	//server is INADDR_ANY so what is written below as host doesn't matter as server listens to all
	host = gethostbyname("127.64.65.1"); //returns hostent structure
	//create sfd
	if((sfd = socket(AF_INET,SOCK_STREAM,0))==-1)
	{
		perror("Socket ready error");
		exit(1);
	}
	//setting up server info to connect
	server_addr.sin_family = AF_INET;
	//should know server port to connect
	server_addr.sin_port = htons(5000);

	server_addr.sin_addr= *((struct in_addr *)host->h_addr); //load with inet_ntoa();
	bzero(&(server_addr.sin_zero),8);
	//clinet ifo is generated by the PC automatically an address is assigned and a port
	if(connect(sfd,(struct sockaddr *)&server_addr,sizeof(struct sockaddr)) == -1)
	{
		perror("connect Error");
		exit(1);
	}
	printf("Connected to Server :Starting to send and receive data\n");
	while(1)
	{
		bytes_recv = recv(sfd,recv_data,maxd,0);
		recv_data[bytes_recv] = '\0';
		printf("Server : %s\n",recv_data );
		printf("ENTER Send data\n");
		fgets(send_data,maxd,stdin);
		send(sfd,send_data,strlen(send_data),0);
		//if q then quit
		if(send_data[0] == 'q')
		{
			close(sfd);
			break;

		}		
	}
}